#! /usr/bin/env bash
curl -X POST -d '{"id":"1","name":"vip1","protocol":"tcp","address":"10.0.0.100","port":"8"}' http://localhost:8080/quantum/v1.0/vips/ | python -m json.tool
curl -X POST -d '{"id":"1","name":"pool1","protocol":"tcp","vip_id":"1"}' http://localhost:8080/quantum/v1.0/pools/ | python -m json.tool
curl -X POST -d '{"id":"1","address":"10.0.0.1","port":"8","pool_id":"1"}' http://localhost:8080/quantum/v1.0/members/ | python -m json.tool
curl -X POST -d '{"id":"2","address":"10.0.0.2","port":"8","pool_id":"1"}' http://localhost:8080/quantum/v1.0/members/ | python -m json.tool
curl http://localhost:8080/quantum/v1.0/vips/ | python -m json.tool
curl http://localhost:8080/quantum/v1.0/pools/ | python -m json.tool
curl http://localhost:8080/quantum/v1.0/members/ | python -m json.tool


